import datetime

def unix_to_ts(value):
    if value is None:
        return None
    return datetime.datetime.utcfromtimestamp(value)

def tinyint_to_bool(value):
    if value is None:
        return None
    return bool(value)

CONVERSION_MAPS = {
    "client_meters":  {
    "meterID": int,
    "clientID": int,

    "sold_date": unix_to_ts,
    "active": tinyint_to_bool,

    "deal_stage": str,
    "meter_status": str,
    "submit_status": str,
    "meter_status_notes": str,
    "supplier_deal_status": str,
    "supplier_deal_status_notes": str,

    "csd": unix_to_ts,
    "ced": unix_to_ts,
    "get_price_ced": unix_to_ts,
    "ced_ooc": tinyint_to_bool,

    "ced_confirmed_by": str,
    "ced_confirmed_by_date": str,
    "top_line": str,

    "measurement_class": str,
    "measurement_class_extended": str,
    "mpan": str,
    "meter_type": str,
    "energised_status": str,

    "meter_tariff_type": str,
    "show_all_tariffs": tinyint_to_bool,
    "meter_pc": int,

    "full_supplier_num": str,
    "account_number": str,
    "meter_mtc": str,
    "meter_llf": str,
    "meter_dist": str,

    "temp_mpan": str,
    "ex_master_date": str,
    "ms_number": str,

    "supplier_from": str,
    "supplier_since": unix_to_ts,
    "supplier_since_unknown": tinyint_to_bool,

    "supplier_from_s_charge": str,
    "supplier_from_unit_charge_all": str,
    "supplier_from_unit_charge_weekday": str,
    "supplier_from_unit_charge_day": str,
    "supplier_from_unit_charge_night": str,
    "supplier_from_unit_charge_weekend": str,

    "supplier_to": str,
    "s_charge": str,
    "first_payment": float,

    "s_charge_units": str,
    "quote_source": str,
    "quote_pricebook": str,
    "source_email": str,

    "capacity_charge": str,
    "capacity_kVa": str,

    "unit_charge_all": str,
    "unit_charge_weekday": str,
    "unit_charge_day": str,
    "unit_charge_night": str,
    "unit_charge_weekend": str,

    "tariff_code": str,
    "consumption": str,
    "consumption_source": str,
    "consumption_added_by": str,

    "contract_duration": str,
    "contract_uplift": int,
    "standing_charge_uplift": float,
    "all_rate_uplift": str,

    "weekday_rate_uplift": float,
    "day_rate_uplift": float,
    "night_rate_uplift": float,
    "weekend_rate_uplift": float,

    "meter_value": str,
    "monthly_budget_plan": str,
    "est_monthly_bill": str,
    "meter_saving": float,

    "ced_notes": str,

    "meter_address_same": tinyint_to_bool,
    "meter_address": str,
    "meter_postcode": str,

    "gas_region_postcode": str,
    "gas_region": str,

    "payment_method": str,
    "authorisationID": str,

    "meter_business_name_same": tinyint_to_bool,
    "meter_business_name": str,

    "billing_address_same": tinyint_to_bool,
    "billing_address": str,
    "billing_postcode": str,

    "meter_notes": str,
    "ced_source": str,

    "ecoes_get_meter_data": str,
    "seen_by_ecoes": tinyint_to_bool,
    "removed": tinyint_to_bool,

    "modified_by": str,

    "port_supplier_to": str,
    "port_supplier_to_ds": str,
    "port_supplier_from": str,
    "port_supplier_from_ds": str,

    "json_price_data": str,

    "timestamp": unix_to_ts,
    "ced_source_timestamp": unix_to_ts,

    "price_reference": str,
    "split_setting": str,

    "metering_charge": str,
    "powwr_bot_number": str,
    "meter_debt": float,

    "ssc": str,

    "ecoes_scrape_timestamp": unix_to_ts,
    "consumption_scrape_timestamp": unix_to_ts,

    "external_sold_till": unix_to_ts,
    "external_sold_instance": str,

    "ced_lock_timestamp": unix_to_ts
},

     # -------------------------------
    # client_status table
    # -------------------------------
    "client_status": {
        "clientID": int,
        "syn_key": str,
        "client_status": str,
        "client_status2": str,
        "renewal_date": int,
        "bucket": int,
        "callback_date": int,
        "callback_time": int,
        "callback_datetime": int,
        "callback_type": str,
        "vip_callback": int,
        "no_contact_datetime": int,
        "sales_agent": int,
        "sales_status": int,
        "sales_outcome_note": int,
        "DMT_status": int,
        "DMT_outcome_note": int,
        "lead_generator": str,
        "lead_status": str,
        "lead_outcome_note": str,
        "new_business_status": str,
        "new_business_outcome_note": int,
        "lead_buddy": int,
        "use_loa_business_status": int,
        "lead_quality_status": int,
        "lead_quality_outcome_note": str,
        "use_loa_business_outcome_note": int,
        "resale_agent": int,
        "resale_status": str,
        "resale_outcome_note": str,
        "quality_sales_outcome": int,
        "quality_sales_note": int,
        "quality_amendment_outcome": int,
        "quality_amendment_note": int,
        "account_manager_status": int,
        "account_manager_outcome_note": int,
        "audit_status": int,
        "account_manager_buddy": int,
        "audit_outcome_note": int,
        "active_department": int,
        "exclusivity_ends": int,
        "modified_by": int,
        "timestamp": int,
        "last_contact_date": int,
        "no_contact_until": int,
        "last_contact_by": int,
        "release_priority": int
    },
    "clients" : {
    "clientID": int,
    "brandID": int,
    "password": str,  # you might later hash or pull from env
    "parentID": int,
    "reference": str,
    "company": str,
    "business_classification": str,
    "search_company": str,
    "address": str,
    "search_address": str,
    "postcode": str,
    "telephone": str,
    "search_telephone": str,
    "FAX": str,
    "email": str,
    "website": str,
    "business_entity": str,
    "business_nature": str,
    "BUSINESSNATURE": str,
    "NACE_CODE": str,
    "primary_contact": int,
    "communications_contact": int,
    "partner_contact": int,
    "employees": str,
    "ALLOCPBA": str,
    "risk_disk_score": str,
    "risk_disk_date": int,
    "risk_disk_userID": int,
    "redflag_score": str,
    "redflag_date": int,
    "redflag_userID": int,
    "FILL2": str,
    "credit_rating_method": str,
    "credit_rating_score": str,
    "credit_rating_date": int,
    "credit_rating_userID": int,
    "IMPORTER": str,
    "EXPORTER": str,
    "IMPPERC": str,
    "EXPPERC": str,
    "FILL1": str,
    "SOURCE": str,
    "PRIMARYSIC": str,
    "SIC1": str,
    "SIC2": str,
    "SIC3": str,
    "ESTTYPE": str,
    "FILL3": str,
    "OWNERSHIP": str,
    "BUSINESSTYPE": str,
    "REGNO": str,
    "VATNO": str,
    "STARTDATE": str,
    "ENDDATE": str,
    "DATECREATED": str,
    "created_date_time": unix_to_ts,
    "TIMECREATED": str,
    "CREATEDBY": str,
    "DATEAMENDED": str,
    "TIMEAMENDED": str,
    "AMENDEDBY": str,
    "LASTCHECKSENT": str,
    "LASTCHECKBACK": str,
    "FLAG1": str,
    "FLAG2": str,
    "FLAG3": str,
    "COMPANY_A": str,
    "DEACTIVATED": str,
    "TELESALES_1": int,
    "TELESALES_2": int,
    "TELESALES_3": int,
    "CLOSER": int,
    "sales_call_complete_agent": int,
    "next_agent": int,
    "moved_in": int,
    "last_recoding_by": int,
    "last_recoding_date": str,
    "last_loa_date": int,
    "moved_out": int,
    "trading_since": int,
    "trading_as": str,
    "creation_date": unix_to_ts,
    "bucket_date": unix_to_ts,
    "modified_by": str,
    "owner": int,
    "assigned_loa": int,
    "assigned_reseller": int,
    "account_manager": int,
    "auto_selected_account_manager": int,
    "account_manager_txt": str,
    "timestamp": unix_to_ts,
    "num_employees": int,
    "annual_turnover": str,
    "account_manager_assigned_on": unix_to_ts,
    "child_classification": str,
    "child_name": str,
    "clim8_authorised_by": str,
    "parent_child_notes": str,
    "include_card_date": int,
    "address_line1": str,
    "address_line2": str,
    "address_line3": str,
    "address_line4": str,
    "num_sites": int,
    "lead_proof": str,
    "search_postcode": str,
    "118_id": int,
    "cot_status": str,
    "encryptedID": str,
    "opening_time": str,
    "closing_time": str,
    "encrypted_clientID": str,
    "test_client": tinyint_to_bool,
    "verbal_script": tinyint_to_bool,
    "notes": str,
    "last_maxcontact_access_by": int
},
"company": {
    "companyID": int,
    "brand": str,
    "companyTitle": str,
    "short_companyTitle": str,
    "companyLogo": str,
    "type": str,
    "contract_delivery": str,
    "companyAddress": str,
    "companyPostcode": str,
    "companyRegNumber": str,
    "companyEmail": str,
    "brokerEmail": str,
    "companyWebsite": str,
    "terminationEmail": str,
    "companyTel": str,
    "brokerTel": str,
    "terminationTel": str,
    "companyMobile": str,
    "companyCurrency": str,
    "gas_price_check_link": str,
    "electric_price_check_link": str,
    "accepted_signatures": str,
    "lead_signatures": str,
    "accepted_signatures_renewals": str,
    "accepted_signature_elec_doc2ID": str,
    "accepted_signature_gas_doc2ID": str,
    "accepted_signatures_supplier_to": str,
    "accepted_signature_contract": str,
    "mpan_new_restrictions": str,
    "contract_duration": int,
    "min_contract_duration": int,
    "termination_notice": str,
    "min_consumption": int,
    "max_consumption": int,
    "elec_min_consumption": int,
    "elec_max_consumption": int,
    "gas_min_consumption": int,
    "gas_max_consumption": int,
    "topline_restrictions": str,
    "half_hourly_max_consumption_elec": int,
    "half_hourly_max_consumption_gas": int,
    "standing_charge_uplift_Electric": float,
    "rate_uplift_Electric": float,
    "min_rate_uplift_Electric": float,
    "rate_uplift_Electric_corporate": float,
    "standing_charge_uplift_Gas": float,
    "rate_uplift_Gas": float,
    "min_rate_uplift_Gas": float,
    "rate_uplift_Gas_corporate": float,
    "electric_commissions": str,
    "gas_commissions": str,
    "ced_sell_limit": int,
    "ced_renewal_limit": int,
    "ced_sell_limit_gas": int,
    "ced_renewal_limit_gas": int,
    "enfore_limit_on_selection": int,
    "accepted_meters": str,
    "hospitality_sector": str,
    "elec_acq_commission_band": str,
    "elec_renewal_commission_band": str,
    "gas_acq_commission_band": str,
    "gas_renewal_commission_band": str,
    "supplier_relationship": str,
    "bill_required_if_renewing": str,
    "bill_required_if_switching": str,
    "hh_accepted": str,
    "minimum_credit_score": str,
    "notes": str,
    "contract_submission_method": str,
    "admin_notes": str,
    "removed": int,
    "default_pricebook_electric": str,
    "default_pricebook_gas": str,
    "modified_by": int,
    "pricebook_note_electric": str,
    "pricebook_note_gas": str,
    "timestamp": int,
    "portal_website": str,
    "accepted_quote_source": str,
    "powwr_supplier_name": str,
    "tendersEmail": str,
    "tendersEmailActive": str
},
"active_users": {
        "userID": int,
        "alias": str,
        "brand": str,
        "access_point": str,
        "sessionID": str,
        "last_seen_reference": str,
        "timestamp": unix_to_ts
    }
 
}